#version 310 es

layout (local_size_x = 8, local_size_y = 8) in;

layout (binding = 0) readonly buffer InBuf {
    uvec4 data[];
} in_buf;

layout (binding = 1) writeonly buffer OutBuf {
    uvec4 data[];
} out_buf;

layout (push_constant) uniform PushConsts {
    uint in_img_width;
    uint out_img_width;
    uint copy_width;
} prop;

void main ()
{
    uint g_x = gl_GlobalInvocationID.x;
    uint g_y = gl_GlobalInvocationID.y;

    if (g_x >= prop.copy_width)
        return;

    out_buf.data[g_y * prop.out_img_width + g_x] = in_buf.data[g_y * prop.in_img_width + g_x];
}
